/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Zhong.view.MainView', {
    extend: 'Ext.navigation.View',
    alias: 'widget.mainview',

    requires: [
        'Ext.navigation.Bar',
        'Ext.Button',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        navigationBar: {
            docked: 'top',
            items: [
                {
                    xtype: 'button',
                    align: 'right',
                    id: '',
                    itemId: 'addTicketButton',
                    iconCls: 'add'
                }
            ]
        },
        items: [
            {
                xtype: 'list',
                title: 'My Plan',
                itemId: 'ticketList',
                itemTpl: [
                    '<div>{title} : {status}</div>'
                ],
                store: 'MyStore',
                onItemDisclosure: true
            }
        ]
    }

});