/*
 * File: app/view/PlanView.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyPlan.view.PlanView', {
    extend: 'Ext.form.Panel',
    alias: 'widget.planview',

    requires: [
        'Ext.form.FieldSet',
        'Ext.field.Slider',
        'Ext.field.Select',
        'Ext.field.TextArea',
        'Ext.field.Hidden',
        'Ext.Button'
    ],

    config: {
        layout: 'vbox',
        items: [
            {
                xtype: 'fieldset',
                items: [
                    {
                        xtype: 'textfield',
                        itemId: 'titleField',
                        label: 'Title',
                        name: 'title'
                    },
                    {
                        xtype: 'sliderfield',
                        itemId: 'importanceField',
                        label: 'Importance',
                        name: 'importance',
                        value: [
                            3
                        ],
                        maxValue: 5,
                        minValue: 1
                    },
                    {
                        xtype: 'selectfield',
                        itemId: 'statusField',
                        label: 'Status',
                        name: 'status',
                        options: [
                            {
                                text: 'Open',
                                value: 'Open'
                            },
                            {
                                text: 'In Progress',
                                value: 'In Progress'
                            },
                            {
                                text: 'Completed',
                                value: 'Completed'
                            }
                        ]
                    },
                    {
                        xtype: 'textareafield',
                        itemId: 'descriptionField',
                        label: 'Description',
                        name: 'description'
                    },
                    {
                        xtype: 'hiddenfield',
                        name: 'id'
                    }
                ]
            },
            {
                xtype: 'button',
                itemId: 'savePlanButton',
                margin: '.3em',
                ui: 'action-round',
                text: 'Save'
            },
            {
                xtype: 'button',
                itemId: 'deletePlanButton',
                margin: '.3em',
                ui: 'decline-round',
                text: 'Delete'
            }
        ]
    }

});