/*
 * File: app/view/TicketView.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Zhong.view.TicketView', {
    extend: 'Ext.form.Panel',
    alias: 'widget.ticketview',

    requires: [
        'Ext.form.FieldSet',
        'Ext.field.Slider',
        'Ext.field.Select',
        'Ext.field.TextArea',
        'Ext.Button'
    ],

    config: {
        itemId: 'saveTicketButton',
        items: [
            {
                xtype: 'fieldset',
                title: 'MyFieldSet',
                items: [
                    {
                        xtype: 'textfield',
                        itemId: 'titleField',
                        label: 'Title'
                    },
                    {
                        xtype: 'sliderfield',
                        itemId: 'importanceField',
                        label: 'Importance',
                        value: [
                            3
                        ],
                        maxValue: 5,
                        minValue: 1
                    },
                    {
                        xtype: 'selectfield',
                        itemId: 'statusField',
                        label: 'Status',
                        options: [
                            {
                                text: 'Open',
                                value: 'Open'
                            },
                            {
                                text: 'In Progress',
                                value: 'In Progress'
                            },
                            {
                                text: 'Completed',
                                value: 'Completed'
                            }
                        ]
                    },
                    {
                        xtype: 'textareafield',
                        itemId: 'descriptionField',
                        label: 'Description'
                    }
                ]
            },
            {
                xtype: 'button',
                text: 'Save'
            }
        ]
    }

});