/*
 * File: app/controller/MyController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Zhong.controller.MyController', {
    extend: 'Ext.app.Controller',

    requires: [
        'Ext.MessageBox'
    ],

    config: {
        refs: {
            addTicketButton: 'mainview #addTicketButton',
            mainView: 'mainview',
            addTicketButton: 'mainview #addTicketButton'
        },

        control: {
            "addTicketButton": {
                tap: 'onAddTicketTap'
            },
            "mainview #ticketList": {
                disclose: 'onTicketDisclose'
            },
            "mainView": {
                pop: 'onNavigationviewPop',
                push: 'onNavigationviewPush'
            },
            "mainview #saveTicketButton": {
                tap: 'onSaveTap'
            }
        }
    },

    onAddTicketTap: function(button, e, eOpts) {
        var mainView = this.getMainView(),
        addTicketButton = this.getAddTicketButton();

        mainView.push({
            xtype: 'ticketview',
            title: 'New ticket'
        });
    },

    onTicketDisclose: function(list, record, target, index, e, eOpts) {
                var mainView = this.getMainView();
                var myForm = mainView.push({
                    xtype: 'ticketview',
                    title: record.get('title'),
                    record: record
                });
    },

    onNavigationviewPop: function(navigationview, view, eOpts) {
        console.log('pop');
        this.getAddTicketButton().show();
    },

    onNavigationviewPush: function(navigationview, view, eOpts) {
        console.log('push');
        this.getAddTicketButton().hide();
    },

    onSaveTap: function(button, e, eOpts) {
        var mainView = this.getMainView(),
            ticketView = button.up('ticketview'),
            store = Ext.getStore('MyStore'),
            values = ticketView.getValues(),
            record = ticketView.getRecord();
        console.log(values);
        if (values.id === '') {
            console.log('add a new record');
            store.add(values);
        } else {
            console.log('update record');
            console.log(record.data);

            record.setData(values);
            record.setDirty();
        }

        console.log(store.sync());

        mainView.pop();
    }

});